service: roadsign-shield-builder

plugins:
  - serverless-offline
  - serverless-stage-manager

frameworkVersion: '>=1.28.0 <2.0.0'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  shield:
    handler: bin/shields
    events:
      - http: GET shield
  shieldsave:
    handler: bin/shieldsave
    events:
      - http:
          path: shield
          method: post
          private: true


custom:
  stages:
    - dev
    - prod
  shieldBucket:
    prod: highwayshield
    dev: highwayshielddev

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  stage: ${opt:stage,'dev'}
  iamManagedPolicies:
    - 'arn:aws:iam::599549803512:policy/shield-save-bucket'
  apiKeys:
    - ${opt:stage}-shieldwrite
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    SHIELDBUCKET: ${self:custom.shieldBucket.${self:provider.stage}}
