service: roadsign-shield-builder

plugins:
  - serverless-offline
  - serverless-stage-manager

frameworkVersion: '>=1.28.0 <2.0.0'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  indexcountapi:
    handler: bin/shields
    events:
      - http: GET shield

custom:
  stages:
    - dev
    - prod

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  stage: ${opt:stage,'dev'}
  apiGateway:
    binaryMediaTypes:
      - '*/*'
