name: Build Shield Builder

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: "checkout github action"
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.4'

      - run: make default